packages:
  - "01-getting-started/**"
  - "02-nextjs-essentials/**"
  - "03-routing-rendering/**"
  - "04-data-fetching/**"
  - "05-data-mutation/**"
  - "06-caching/**"
  - "07-optimizations/**"
  - "08-authentication/**"
